<?php

namespace App\Services\Audit;

use App\Models\PasswordResetRequest;
use App\Support\Legacy\LegacyIds;
use App\Support\Legacy\PersianText;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use RuntimeException;
use Throwable;

/**
 * The password-recovery workflow: request → admin approval → 8-character code.
 *
 * Ported from `app/services/audit.py`.  There is **no email and no SMS** anywhere in
 * this flow, which is worth stating because it is the first thing a reader assumes:
 * a user asks for a reset, an administrator approves it, and the code is then shown
 * to the user by the administrator.
 *
 * Four security decisions are preserved exactly, because each one closes a real
 * hole:
 *
 * 1. **The flow fails closed without `HASTAMA_HMAC_SECRET`.**  The code is stored as
 *    an HMAC-SHA256 digest rather than in clear, so without a key the digest would
 *    provide no integrity and recovery is disabled.  In `DEBUG` mode only, an
 *    ephemeral per-process key is used as a development convenience.
 * 2. **Single generic rejection message** (`کد بازیابی نامعتبر است.`) for every
 *    failure an unauthenticated caller can reach.  `/forgot_password` answers with a
 *    *decoy* request id for unknown accounts, so anything distinguishable here would
 *    turn the endpoint into a username-enumeration oracle.  That is why the
 *    reason-specific messages ("expired", "already processed") are only produced
 *    **after** the caller has proven possession of the code.
 * 3. **A hard attempt cap** — once `code_attempts` reaches `max_attempts` the code
 *    is disabled (status `expired`) on the next attempt, and the caller still sees
 *    the generic message.
 * 4. **Constant-time comparison** of the digest.
 *
 * The code alphabet is `A–Z0–9`, eight characters long, because that is what the
 * existing Python generated.  (The `secrets.token_uppercase` the original comment
 * mentions does not exist in Python's `secrets` module — the working code is an
 * explicit `secrets.choice` loop, which is what is reproduced here.)
 */
final class RecoveryCodeService
{
    /** Every rejection an unauthenticated caller can reach uses this one message. */
    public const CODE_REJECTED_MESSAGE = 'کد بازیابی نامعتبر است.';

    /** Code length and alphabet, as generated by the Python implementation. */
    public const CODE_LENGTH = 8;

    public const CODE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

    /** Default validity of an issued code, in minutes. */
    public const DEFAULT_TTL_MINUTES = 60;

    /**
     * Whether the recovery flow may be used at all.
     *
     * False when no HMAC secret is configured, unless debug mode is on.
     */
    public function available(): bool
    {
        return $this->secret() !== null;
    }

    /**
     * Create a pending reset request for a username.
     *
     * Returns the generated request id, or null when it could not be persisted —
     * the caller still answers with the unified message (and a decoy id), because
     * the request id is what the operator will ask for.
     */
    public function createRequest(string $username, ?string $ipAddress, ?string $userAgent): ?string
    {
        $requestId = LegacyIds::requestId();

        try {
            PasswordResetRequest::query()->insert([
                'request_id' => $requestId,
                'username' => $username,
                'ip_address' => $ipAddress !== null ? mb_substr($ipAddress, 0, 45) : null,
                'user_agent' => $userAgent !== null ? mb_substr($userAgent, 0, 500) : null,
                'status' => PasswordResetRequest::STATUS_PENDING,
            ]);

            return $requestId;
        } catch (Throwable $exception) {
            Log::warning('password reset request could not be persisted', [
                'exception' => $exception::class,
                'reason' => $exception->getMessage(),
            ]);

            return null;
        }
    }

    /**
     * Approve a pending request and return the one-time code.
     *
     * The plaintext code is returned **once**, to the administrator who approved it;
     * only its digest is stored.
     *
     * @return array{success: bool, code?: string, message?: string, code_unavailable?: bool}
     */
    public function approve(string $requestId, string $adminUsername, int $ttlMinutes = self::DEFAULT_TTL_MINUTES): array
    {
        if (! $this->available()) {
            return [
                'success' => false,
                'message' => 'کلید HASTAMA_HMAC_SECRET تنظیم نشده است؛ بازیابی رمز عبور غیرفعال است.',
                'code_unavailable' => true,
            ];
        }

        try {
            $code = $this->generateCode();
            $expiresAt = now()->addMinutes($ttlMinutes);

            $changed = PasswordResetRequest::query()
                ->where('request_id', $requestId)
                ->where('status', PasswordResetRequest::STATUS_PENDING)
                ->update([
                    'status' => PasswordResetRequest::STATUS_APPROVED,
                    'recovery_code' => $this->hashCode($code),
                    'code_expires_at' => $expiresAt,
                    'approved_by' => $adminUsername,
                    'approved_at' => now(),
                ]);

            if ($changed === 0) {
                return ['success' => false, 'message' => 'درخواست یافت نشد یا قبلاً پردازش شده است.'];
            }

            return [
                'success' => true,
                'code' => $code,
                'expires' => $expiresAt->toIso8601String(),
            ];
        } catch (Throwable $exception) {
            Log::error('password reset approval failed', ['exception' => $exception::class]);

            return ['success' => false, 'message' => 'خطای داخلی سرور'];
        }
    }

    /** Refuse a pending request. */
    public function reject(string $requestId, string $adminUsername): bool
    {
        try {
            return PasswordResetRequest::query()
                ->where('request_id', $requestId)
                ->where('status', PasswordResetRequest::STATUS_PENDING)
                ->update([
                    'status' => PasswordResetRequest::STATUS_REJECTED,
                    'approved_by' => $adminUsername,
                ]) > 0;
        } catch (Throwable $exception) {
            Log::warning('password reset rejection failed', ['exception' => $exception::class]);

            return false;
        }
    }

    /**
     * Verify a code and, on success, mark the request completed.
     *
     * @return array{success: bool, username?: string, message?: string}
     */
    public function verify(string $requestId, string $code): array
    {
        if (! $this->available()) {
            return ['success' => false, 'message' => 'بازیابی رمز عبور در این نصب غیرفعال است.'];
        }

        try {
            $request = PasswordResetRequest::query()->where('request_id', $requestId)->first();

            if ($request === null) {
                // Identical to the wrong-code answer: /forgot_password hands out decoy
                // ids for unknown accounts, so this must not be distinguishable.
                return ['success' => false, 'message' => self::CODE_REJECTED_MESSAGE];
            }

            if ($request->code_attempts >= $request->max_attempts) {
                PasswordResetRequest::query()
                    ->where('request_id', $requestId)
                    ->update(['status' => 'expired']);

                return ['success' => false, 'message' => self::CODE_REJECTED_MESSAGE];
            }

            if (! hash_equals((string) $request->recovery_code, $this->hashCode($code))) {
                PasswordResetRequest::query()
                    ->where('request_id', $requestId)
                    ->update(['code_attempts' => $request->code_attempts + 1]);

                return ['success' => false, 'message' => self::CODE_REJECTED_MESSAGE];
            }

            // The caller has proven possession of the code. Everything below is
            // operational feedback rather than an oracle.
            if ($request->code_expires_at !== null && $request->code_expires_at->isPast()) {
                PasswordResetRequest::query()
                    ->where('request_id', $requestId)
                    ->update(['status' => 'expired']);

                return ['success' => false, 'message' => 'کد بازیابی منقضی شده است.'];
            }

            if ($request->status !== PasswordResetRequest::STATUS_APPROVED) {
                return ['success' => false, 'message' => 'این درخواست قبلاً پردازش شده است.'];
            }

            PasswordResetRequest::query()
                ->where('request_id', $requestId)
                ->update([
                    'status' => PasswordResetRequest::STATUS_COMPLETED,
                    'completed_at' => now(),
                ]);

            return ['success' => true, 'username' => (string) $request->username];
        } catch (Throwable $exception) {
            Log::error('recovery code verification failed', ['exception' => $exception::class]);

            return ['success' => false, 'message' => 'خطای داخلی سرور'];
        }
    }

    /** Generate a code from the legacy alphabet. */
    public function generateCode(): string
    {
        $limit = strlen(self::CODE_ALPHABET) - 1;
        $code = '';

        for ($i = 0; $i < self::CODE_LENGTH; $i++) {
            $code .= self::CODE_ALPHABET[random_int(0, $limit)];
        }

        return $code;
    }

    /**
     * The stored digest of a code: HMAC-SHA256, hex encoded.
     *
     * Note that the stored value is compared against a freshly computed digest, so
     * the **case of a request id does not matter** but the case of the *code* does —
     * codes are generated upper-case and compared upper-case, exactly as before.
     */
    public function hashCode(string $code): string
    {
        $secret = $this->secret();

        if ($secret === null) {
            throw new RuntimeException('HASTAMA_HMAC_SECRET is not configured');
        }

        return hash_hmac('sha256', PersianText::strip($code), $secret);
    }

    /** Whether a candidate request id has the legacy shape. */
    public function isValidRequestId(?string $requestId): bool
    {
        return LegacyIds::isValid($requestId);
    }

    /**
     * Whether a candidate code has the legacy shape (`^[A-Z0-9]{8}$`).
     *
     * Transcribed from `validate_recovery_code`, including the fact that the check
     * happens **before** any lookup: a malformed code is rejected without touching
     * the database.
     */
    public function isValidCode(?string $code): bool
    {
        return is_string($code) && preg_match('/^[A-Z0-9]{'.self::CODE_LENGTH.'}$/', PersianText::strip($code)) === 1;
    }

    /**
     * The HMAC secret, or null when the flow must stay disabled.
     *
     * The `DEBUG` fallback mirrors the Python implementation: an ephemeral
     * per-process key so a local checkout keeps working, with a warning in the log.
     * Codes issued under it do not survive a restart.
     */
    private function secret(): ?string
    {
        $secret = PersianText::strip((string) config('hastama.recovery.hmac_secret', ''));

        if ($secret !== '') {
            return $secret;
        }

        if (! config('app.debug')) {
            return null;
        }

        $ephemeral = Cache::rememberForever('hastama.recovery.ephemeral_secret', function (): string {
            Log::warning('HASTAMA_HMAC_SECRET is not set — using an ephemeral development key');

            return bin2hex(random_bytes(32));
        });

        return $ephemeral;
    }
}
